config/routes.rb
SampleApp::Application.routes.draw do

resources :users
resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'
  
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/sample', to: 'static_pages#samplelesson'
  match '/product', to: 'static_pages#product'
    
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  











end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#


class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private
  
	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

protect_from_forgery
include SessionsHelper

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user
		else
			flash.now[:error] = "Invalid email/password combination." 
			render 'new'
		end
	end
	
	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
  def samplelesson
  end
  
  def product
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :signed_in_user, 	only: [:edit, :update, :index]
	before_filter :correct_user, 	only: [:edit, :update]
	before_filter :admin_user,		only: [:destroy]
	
	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end
  
	def create
		@user = User.new(params[:user])
		if @user.save
			sign_in @user
			flash[:success] = "Thanks for signing up and welcome to Boost English!"
			redirect_to sample_path
		else
			render 'new'
		end
	end
	
	def edit
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			flash[:success] = "Profile updated"
			sign_in @user
			redirect_to @user
		else
			render 'edit'
		end
	end
	
	def index
		@users = User.paginate(page: params[:page])
	end
	
	private
	
		def signed_in_user
			redirect_to signin_path, notice: "Please sign in." unless signed_in?
		end
		
		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_path) unless current_user?(@user)
		end
		
	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User deleted successfully."
		redirect_to users_path
	end
end
  

app/helpers/application_helper.rb
module ApplicationHelper

	#returns the full title on a per-page basis
	def full_title(page_title)
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		current_user = user
	end
	
	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end
	
	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end
	
	def current_user?(user)
		user == current_user
	end
	
	def sign_out
		@current_user = nil
		cookies.delete(:remember_token)
	end
	
	
	private
	
		def user_from_remember_token
			remember_token = cookies[:remember_token]
			User.find_by_remember_token(remember_token) unless remember_token.nil?
		end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

 
# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorial.org/">EnglishGeek/书虫英语</a>
		by OWL Productions
	</small>
	<nav>
		<ul>
			<li><%= link_to "About us", about_path %>
			<li><%= link_to "Contact", contact_path %>
			<li><a href="http://news.railstutorial.org/"> News </a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" style="margin-bottom: 0px; padding: 0px">
		<div class="navbar-inner">
			<div class="container-fluid">
				<%= link_to "TUTORi English", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Home",		root_path %></li>
						<% if signed_in? %>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b></li>
						<ul class="dropdown-menu">
							<li><%=link_to "Profile", current_user %></li>
							<li><%=link_to "Settings", edit_user_path(current_user) %></li>
							<li><%= link_to "Users", users_path %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Sign out", signout_path, method: "delete" %>
							</li>
						<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
						<li><%= link_to "New user? Sign up now!", signup_path %></li>	
						<% end %>
				</nav>
			</div>
		</div>
	</header>
	
	
   
	

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<div class="container-fluid">
		<%= render 'layouts/header' %>
	    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
	<% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<div class="container">
	<div class="row">
		<div class="span12">
			<h1>About Us</h1>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<p>
				<b>What is Language Works?</b></br>
				We are a startup which makes foreign language education work
				the way that it is supposed to. Based on our own experiences
				teaching and learning foreign languages, we know that you don't
				learn a language in a classroom. You learn a language by speaking it.
				Which is what we're trying to do here.
			</p>
		</div>
	</div>
	
	<div class="row">
		<div class="span12">
			<p>
				<b>Why is language works different from other tutoring agencies?</b></br>
				Language works is different because we're online. Depending on your location,
				your schedule, and your budget, it is not always convenient to hire a
				foreign tutor to come to your home. Language Works makes this process much easier,
				by allowing you to meet daily with a foreign tutor in the US or the UK from
				the comfort of your own home.
			</p>	
		</div>
	</div>
	
	<div class="row">
		<div class="span12">
			<p>
				<b>What do I get with language works?</b></br>
				
				With language works you get a highly-qualified native-speaking English tutor 
				to meet with several times each week. This is what we say, and this is what you get.				Unlike a lot of the tutoring agencies operating in China today,
				we don't falsify our teacher's qualifications. Because we don't need to.
				We only hire people with quality educational and professional experience.
				We hire exclusively from top universities in the United States and United Kingdom.			
			</p>
		</div>
	</div>
	
	<div class="row">
		<div class="span12">
			<p>
				<b>How does language works guarantee quality?</b></br>
				Language Works guarantees quality with a personal promise.
				Each of our teachers is interviewed by our founders personally, who bring 
				several years of experience in teaching and tutoring English students
				in Shanghai. We personally look for the qualities that make an excellent
				English tutor - educated, friendly, energetic, and reliable. 
			</p>
		</div>
	</div>
	
	<div class="row">
		<div class="span12">
			<p>
				<b>Why is language works so much less expensive than other langauge schools?</b></br>
				Because we leverage the power of technology to keep costs down.
				Where other language schools waste money on excessive salespeople and
				and staff, we rely on software to make everything happen automatically.
				And where other schools waste money on expensive advertising,
				we rely on satisfied customers and social networks to do our advertising for us.
				Which means that you get a better product for a lower price.
			</p>
		</div>
	</div>
			
	<div class="row">
		<div class="span12">
			<p>
				<b>How do I get started?</b></br>
				Get started by checking out our <%= link_to "introductory video", signup_path %>.
				This will explain what we do in a bit more detail. If you like what you see, go ahead and create
				a free account and check out a few free sample lessons. If you think you're interested, you can
				check out our <%= link_to "lessons plans" %> and start taking lessons.
				
			</p>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact')%>
<h1> Contact </h1>
<p>
  Contact us at
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
    <h1>Help</h1>
    <p>
      Having trouble? Questions? Comments? Just want to say hi?
	  <%= link_to "Contact us", contact_path %>
    </p>

app/views/static_pages/home.html.erb
<div class="headerimage"><img src="homebg.jpg" style="position: absolute; width: 100%; max-height: 380px; margin-top: -10px; z-index:-1;" />
	<div class="container">
	<div class="hero-unit">
		<h1>TUTORi English</h1>
		<h2>Affordable one-on-one English language tutoring from the comfort of your own home!</h2>
		<%= link_to "Get Started!", signup_path, class: "btn btn-large btn-primary" %>
		<%= link_to "What Do We Do?", about_path, class: "btn btn-large btn-primary" %> 
	</div>
	<div class="row" style="margin: 50px 5px">
		<div class="span12">
		<h1>The most efficient way to learn a foreign language. Guaranteed.</h2>
		<h2>By combining the latest in linguistics technology with state-of-the-art communications technology, Tutori English seeks to bring effective language learning to people worldwide.</p>
	  </div>
	</div>
      <div class="row">
        <div class="span4" id="homethumbcont">
          <h2>BOOST Oral English</h2>
		  <img src="/convo.jpg", class="thumbnail"/>
           <p style="padding: 5px">In a globalized world, spoken English is the key to meeting people, making connections, and getting to know the world outside China. No matter who you are, BOOST oral English is for you.</p>
          <p style="margin-left: 15px"><a class="btn" href="#">Learn More &raquo;</a></p>
        </div>
        <div class="span4" id="homethumbcont">
          <h2>BOOST Your Career</h2>
		  <img src="/stairs.jpg", class="thumbnail"/>
           <p style="padding: 5px">Whether you're working for a multinational, or a local company with customers abroad, send your career to the next level with our award winning global business English program.</p>
          <p style="margin-left: 15px"><a class="btn" href="#">Learn More &raquo;</a></p>
       </div>
        <div class="span4" id="homethumbcont">
          <h2>BOOST Kids</h2>
		  <img src="/youth.jpg", class="thumbnail"/>
          <p style="padding: 5px">More and more, English is the international language of education. Make sure that your child is not left behind. Get started today with the Boost english kids program.</p>
          <p style="margin-left: 15px"><a class="btn" href="#">Learn More &raquo;</a></p>
        </div>
      </div>

</div>


app/views/static_pages/product.html.erb
<div class="container">
	<div class="row">
		<div class="span8">
		<h2>Here we can have a final sales page explaining
		how much our product costs and what the benefits of signing up are</h2>
		</div>
		<div class="span4">
		<h2>This is for the alipay/unionpay plugin</h2>
		</div>
	</div>
	<div class="row">
	<h1>Some further copy about what a great deal this product is
	and possibly another faq or some pictures</h1>
	</div>
</div>

app/views/static_pages/samplelesson.html.erb
<div class="container">
<h1>Welcome to the Free English Boost Sample Lesson</h1>
	<div class="row">
		<div class="span8">
		<iframe width="480" height="360" src="http://www.youtube.com/embed/_tDxofzvTfU" frameborder="0" allowfullscreen></iframe>
		</div>
		<div class="span4">
		<h2>put the sales bullet points here!</h2>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<h2><%= link_to "Get Started!", product_path, class: "btn btn-large btn-primary" %></h2>
		</div>
	</div>

</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
  <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
		<%= gravatar_for user, size: 52 %>
		<%= link_to user.name, user %>
		<% if current_user.admin? && !current_user?(user) %>
			| <%= link_to "delete", user, method: :delete, confirm: "Delete User?"%>
		<%= end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1> Sign up </h1>

	
	<div class="row-fluid">
		<div class="span8">
				<embed src="http://player.youku.com/player.php/sid/XNDA2NTIyODAw/v.swf" allowFullScreen="true" quality="high" width="480" height="400" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash"></embed>
			</div>
		<div class="span4">
			<%= form_for(@user) do |f| %>
				<%= render 'shared/error_messages' %>
				<%= f.label :name %>
				<%= f.text_field :name %>
	
				<%= f.label :email %>
				<%= f.text_field :email %>

				<%= f.label :password %>
				<%= f.password_field :password %>

				<%= f.label :password_confirmation, "Confirm Password" %>
				<%= f.password_field :password_confirmation %>
				<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
			<% end %>
		</div>	
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
	<div class="row">
		<aside class="span4">
			<section>
				<h1>
					<%= gravatar_for @user %>
					<%= @user.name %></h1>
				</h1>
			</section>
		</aside>
	</div>